# Based on http://kripken.github.io/emscripten-site/docs/compiling/Travis.html

notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

git:
  submodules: false

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-ubuntu:latest bash

script:
  - make
