dist: focal

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-ubuntu:latest bash

script:
  - make web

notifications:
  email: false
