# Based on http://kripken.github.io/emscripten-site/docs/compiling/Travis.html

notifications:
  email: false

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-ubuntu:latest bash

script:
  - docker exec -it emscripten apt-get update
  - docker exec -it emscripten apt-get install -y autoconf bison re2c
  - docker exec -it emscripten bash build.sh
