version: '3'

services:

  emscripten-builder:
    image: seanmorris/php-emscripten-builder
    user: "${UID:-0}:${GID:-0}"
    build:
      context: ./
      dockerfile: emscripten-builder.dockerfile
    environment:
      EMCC_CORES: 8
      ENVIRONMENT: ${ENVIRONMENT:-web}
      USER_ID: ${UID:-1000}
    volumes:
      - ./:/src
      - /tmp/emsdk-cache:/emsdk/upstream/emscripten/cache/
      - ./.cache:/emsdk_portable/.data/cache/asmjs/
      - ${PHP_DIST_DIR:-./dist}:/src/dist
    command: [bash]
