version: 2.1

commands:

workflows:
  version: 2

  build-test-flow:
    jobs:
      - make-archives

      - make-test-8-3-static:
          requires:
            - make-archives
      - make-test-8-3-shared:
          requires:
            - make-archives
      - make-test-8-3-dynamic:
          requires:
            - make-archives

      - make-test-8-2-static:
          requires:
            - make-archives
      - make-test-8-2-shared:
          requires:
            - make-archives
      - make-test-8-2-dynamic:
          requires:
            - make-archives

      - make-test-8-1-static:
          requires:
            - make-archives
      - make-test-8-1-shared:
          requires:
            - make-archives
      - make-test-8-1-dynamic:
          requires:
            - make-archives

      - make-test-8-0-static:
          requires:
            - make-archives
      - make-test-8-0-shared:
          requires:
            - make-archives
      - make-test-8-0-dynamic:
          requires:
            - make-archives

jobs:

  make-archives:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - checkout
      - run: npm install
      - run: cp .circleci/.env_8.3.ci .env
      - run: time make archives
      - persist_to_workspace:
          root: ~/
          paths:
            - project/

  make-test-8-3-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.3.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-3-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.3-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-3-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.3-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-2-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
            at: ~/
      - run: cp .circleci/.env_8.2.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-2-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.2-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-2-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.2-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-1-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
            at: ~/
      - run: cp .circleci/.env_8.1.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-1-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.1-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-1-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.1-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-0-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
            at: ~/
      - run: cp .circleci/.env_8.0.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-0-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.0-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-0-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.0-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test
