version: 2.1

commands:

workflows:
  version: 2

  build-test-flow:
    jobs:
      - make-test

jobs:
  make-test:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - checkout
      - run: npm install
      - run: cp .circleci/.env.ci .env
      - run: make show-ports lib/lib/libpng.a test
