version: 2.1

commands:

workflows:
  version: 2

  build-test-flow:
    jobs:
      - make-test-8-3
      - make-test-8-2
      - make-test-8-1
      - make-test-8-0

jobs:

  make-test-8-3:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - run: cp .circleci/.env_8.3.ci .env
      - run: time make image test

  make-test-8-2:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - run: cp .circleci/.env_8.2.ci .env
      - run: time make image test

  make-test-8-1:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - run: cp .circleci/.env_8.1.ci .env
      - run: time make image test

  make-test-8-0:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: xlarge
    steps:
      - run: cp .circleci/.env_8.0.ci .env
      - run: time make image test
