version: 2.1

commands:

workflows:
  version: 2

  build-test:
    jobs:
      - make

jobs:
  make:
    parallelism: 1
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - run: npm install
      - run: make test

