version: 2.1

commands:

  setup:
    steps:
      - run: sudo apt update

workflows:
  version: 2

  build-push-deploy:
    jobs:
      - make -j8

jobs:
  make:
    parallelism: 1
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: make

