name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y docker-compose
      - run: npm install
      - run: cp .circleci/.env_8.3.ci .env
      - run: make test
  # test-8-2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: npm install
  #     - run: cp .circleci/.env_8.2.ci .env
  #     - run: make test PHP_VERSION=8.2
  # test-8-1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: npm install
  #     - run: cp .circleci/.env_8.1.ci .env
  #     - run: make test PHP_VERSION=8.1
  # test-8-0:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: npm install
  #     - run: cp .circleci/.env_8.0.ci .env
  #     - run: make test PHP_VERSION=8.0
