name: Test
on: [push]
jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: make image save-image
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
  test-8-3:
    name: Test 8.3
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.3.ci .env
      - run: make image test

  test-8-2:
    name: Test 8.2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.2.ci .env
      - run: make image test PHP_VERSION=8.2

  test-8-1:
    name: Test 8.1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.1.ci .env
      - run: make image test PHP_VERSION=8.1

  test-8-0:
    name: Test 8.0
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.0.ci .env
      - run: make image test PHP_VERSION=8.0


  test-dynamic:
    name: 8.3 Dynamic
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.3-dynamic.ci .env
      - run: make image test

  test-8-2-dynamic:
    name: 8.2 Dynamic
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.2-dynamic.ci .env
      - run: make image test PHP_VERSION=8.2

  test-8-1-dynamic:
    name: 8.1 Dynamic
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.1-dynamic.ci .env
      - run: make image test PHP_VERSION=8.1

  test-8-0-dynamic:
    name: 8.0 Dynamic
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.0-dynamic.ci .env
      - run: make image test PHP_VERSION=8.0


  test-shared:
    name: 8.3 Shared
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.3-shared.ci .env
      - run: make image test

  test-8-2-shared:
    name: 8.2 Shared
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.2-shared.ci .env
      - run: make image test PHP_VERSION=8.2

  test-8-1-shared:
    name: 8.1 Shared
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.1-shared.ci .env
      - run: make image test PHP_VERSION=8.1

  test-8-0-shared:
    name: 8.0 Shared
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: cp .circleci/.env_8.0-shared.ci .env
      - run: make image test PHP_VERSION=8.0
